package com.codingbingoZTT.BanmaReader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig tipDaoConfig;

    private final BookDao bookDao;
    private final ChapterDao chapterDao;
    private final TipDao tipDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        tipDaoConfig = daoConfigMap.get(TipDao.class).clone();
        tipDaoConfig.initIdentityScope(type);


        bookDao = new BookDao(bookDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        tipDao = new TipDao(tipDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Chapter.class, chapterDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        tipDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public TipDao getTipDao() {
        return tipDao;
    }
}
